### ISSUE TITLE
Exotics 

### ISSUE THREAD

**Issue by ctrlcmdshft** [Division2-Loadout/ui#1]
Make it so you can only equip one Exotic weapon and one Exotic gear piece at the same time just like in game

**Comment by Division2-Loadout** [comment]
Hello, thanks a lot for opening the initial issue for this project! :)

I was planning to add a warning but not locking-out the user of doing it. I could add both options (allowing the user to switch it on/off). The reason of this, is that I want the app to primarily be an equipment-tracker and not for making builds, but it could become both I believe.
What I mean with the above is that, for example you could have a loadout saved for tracking exotics that you are chasing/tracking for better rolls. 

![image](https://github.com/Division2-Loadout/ui/assets/141663986/094231a9-4e77-4c58-9ca4-e72657a6c723)

About showing the warning, It is a similar case with the attributes as the app allows you to add 2 attributes that are the same and that is not possible in game, I could also add a switch on/off for the user to decide on the behaviour.
